services:
  - type: web
    name: resume-analyzer
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn resume_analyzer.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: GEMINI_API_KEY
        sync: false
